# Generated by Django 6.0.6 on 2026-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('Update_time', models.TimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
    ]
