# Generated by Django 6.0.6 on 2026-06-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coment',
            name='subect',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
