# Generated by Django 6.0.6 on 2026-06-19 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_alter_coment_message_alter_coment_subect'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='Update_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coment',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
