# Generated by Django 6.0.6 on 2026-06-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_coment_update_time_coment_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='subect',
            new_name='subject',
        ),
    ]
