# Generated by Django 6.0.6 on 2026-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=220)),
                ('contact', models.TextField()),
                ('counted_viow', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('published_data', models.TimeField(null=True)),
                ('created_data', models.TimeField(auto_now_add=True)),
                ('Updated_data', models.TimeField(auto_now=True)),
            ],
        ),
    ]
