# Generated by Django 6.0.6 on 2026-07-04 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=220)),
                ('contact', models.TextField()),
                ('counted_viow', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('published_data', models.DateTimeField(null=True)),
                ('image', models.ImageField(default='blog/default.jpg', upload_to='blog/')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('Updated_data', models.DateTimeField(auto_now=True)),
                ('aother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='blog.category')),
            ],
        ),
    ]
